name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every 24 hours
  workflow_dispatch:      # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Shubsriv001
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/snake.svg"
          branch: output
